version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-filmes
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: filmesdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
